accelerate launch --num_processes 2 --num_machines 1 --dynamo_backend no  ../../train_controlnext.py --pretrained_model_name_or_path "../../SDXL_model" \
--pretrained_vae_model_name_or_path "../../VAE_model" \
--variant fp16 \
--train_batch_size 2 \
--use_safetensors \
--output_dir "example" \
--logging_dir "logs" \
--resolution 1024 \
--gradient_checkpointing \
--set_grads_to_none \
--proportion_empty_prompts 0.2 \
--controlnet_scale_factor 1.0 \
--mixed_precision fp16 \
--enable_xformers_memory_efficient_attention \
--dataset_name "Nahrawy/VIDIT-Depth-ControlNet" \
--image_column "image" \
--conditioning_image_column "depth_map" \
--caption_column "caption" \
--validation_prompt "a stone tower on a rocky island" \
--validation_image "condition_0.png"